TECHNOLOGIES = {
    "Python": [
        "Variables", "Data Types", "Operators", "Input / Output", "Conditions",
        "Loops", "Functions", "Strings", "Lists", "Tuples", "Sets",
        "Dictionaries", "File Handling", "Exception Handling", "Modules", "OOP",
        "Iterators", "Generators", "Lambda", "Decorators", "Virtual Environment",
        "PIP", "NumPy", "Pandas", "Matplotlib", "APIs", "JSON", "SQLite",
        "Flask", "Django", "Mini Projects", "Advanced Projects",
    ],
    "Java": [
        "Variables", "Data Types", "Operators", "Control Flow", "Loops",
        "Methods", "Arrays", "Strings", "OOP Basics", "Inheritance",
        "Polymorphism", "Abstraction", "Interfaces", "Exception Handling",
        "Collections", "Generics", "File I/O", "Multithreading", "Lambda Expressions",
        "Streams API", "JDBC", "Maven / Gradle", "JUnit Testing", "Spring Basics",
        "Spring Boot", "REST APIs", "Mini Projects", "Advanced Projects",
    ],
    "C": [
        "Variables", "Data Types", "Operators", "Input / Output", "Conditions",
        "Loops", "Functions", "Arrays", "Strings", "Pointers", "Structures",
        "Unions", "Dynamic Memory Allocation", "File Handling", "Preprocessor",
        "Bitwise Operations", "Recursion", "Command Line Arguments",
        "Mini Projects", "Advanced Projects",
    ],
    "C++": [
        "Variables", "Data Types", "Operators", "Conditions", "Loops",
        "Functions", "Arrays", "Strings", "Pointers", "References",
        "OOP Basics", "Constructors / Destructors", "Inheritance", "Polymorphism",
        "Operator Overloading", "Templates", "STL Containers", "STL Algorithms",
        "Exception Handling", "File Handling", "Smart Pointers", "Lambda Expressions",
        "Mini Projects", "Advanced Projects",
    ],
    "JavaScript": [
        "Variables", "Data Types", "Operators", "Conditions", "Loops",
        "Functions", "Arrays", "Objects", "Strings", "DOM Manipulation",
        "Events", "ES6 Features", "Arrow Functions", "Destructuring",
        "Spread / Rest", "Promises", "Async / Await", "Fetch API", "JSON",
        "Local Storage", "Modules", "Error Handling", "Closures", "Prototypes",
        "Event Loop", "Mini Projects", "Advanced Projects",
    ],
    "React": [
        "JSX", "Components", "Props", "State", "Events", "Conditional Rendering",
        "Lists and Keys", "Forms", "useState", "useEffect", "useContext",
        "useRef", "useMemo", "useCallback", "Custom Hooks", "React Router",
        "Context API", "Redux Basics", "API Integration", "Error Boundaries",
        "Performance Optimization", "Testing", "Mini Projects", "Advanced Projects",
    ],
    "Node.js": [
        "Node Basics", "NPM", "Modules", "File System", "Events", "Streams",
        "HTTP Module", "Express Basics", "Routing", "Middleware",
        "REST API Design", "Error Handling", "Authentication", "JWT",
        "MongoDB Integration", "SQL Integration", "WebSockets", "Testing",
        "Deployment", "Mini Projects", "Advanced Projects",
    ],
    "SQL": [
        "Databases Basics", "SELECT", "WHERE", "ORDER BY", "INSERT", "UPDATE",
        "DELETE", "Aggregate Functions", "GROUP BY", "HAVING", "Joins",
        "Subqueries", "Indexes", "Views", "Stored Procedures", "Transactions",
        "Normalization", "Constraints", "Window Functions", "Query Optimization",
        "Mini Projects", "Advanced Projects",
    ],
    "Data Structures": [
        "Arrays", "Strings", "Linked Lists", "Stacks", "Queues", "Hash Tables",
        "Trees", "Binary Search Trees", "Heaps", "Graphs", "Recursion",
        "Sorting Algorithms", "Searching Algorithms", "Two Pointers",
        "Sliding Window", "Dynamic Programming", "Greedy Algorithms",
        "Backtracking", "Time Complexity", "Space Complexity",
        "Mini Projects", "Advanced Projects",
    ],
    "Machine Learning": [
        "Python for ML", "NumPy", "Pandas", "Data Visualization",
        "Data Preprocessing", "Feature Engineering", "Linear Regression",
        "Logistic Regression", "Decision Trees", "Random Forests", "SVM",
        "KNN", "Naive Bayes", "Clustering", "Dimensionality Reduction",
        "Model Evaluation", "Cross Validation", "Hyperparameter Tuning",
        "Scikit-learn", "Neural Network Basics", "Mini Projects", "Advanced Projects",
    ],
    "AI": [
        "AI Fundamentals", "Search Algorithms", "Knowledge Representation",
        "Machine Learning Basics", "Deep Learning Basics", "Neural Networks",
        "CNNs", "RNNs", "Transformers", "NLP Basics", "Computer Vision Basics",
        "Prompt Engineering", "LLM APIs", "LangChain", "Vector Databases",
        "RAG", "AI Agents", "AI Ethics", "Mini Projects", "Advanced Projects",
    ],
    "Data Science": [
        "Python Basics", "NumPy", "Pandas", "Data Cleaning", "EDA",
        "Data Visualization", "Matplotlib", "Seaborn", "Statistics Basics",
        "Probability", "Hypothesis Testing", "SQL for Data Science",
        "Machine Learning Basics", "Feature Engineering", "Model Building",
        "Model Evaluation", "Dashboards", "Storytelling with Data",
        "Big Data Basics", "Mini Projects", "Advanced Projects",
    ],
    "Cyber Security": [
        "Security Fundamentals", "Networking Basics", "Operating Systems",
        "Linux Basics", "Cryptography Basics", "Web Security", "OWASP Top 10",
        "Network Security", "Firewalls", "IDS / IPS", "Vulnerability Assessment",
        "Penetration Testing Basics", "Social Engineering", "Malware Analysis Basics",
        "Incident Response", "Security Tools", "Ethical Hacking Basics",
        "Compliance and Standards", "Mini Projects", "Advanced Projects",
    ],
    "Cloud Computing": [
        "Cloud Fundamentals", "IaaS / PaaS / SaaS", "Virtualization",
        "Linux Basics", "Networking Basics", "AWS Basics", "Azure Basics",
        "GCP Basics", "Compute Services", "Storage Services", "Databases in Cloud",
        "IAM and Security", "Load Balancing", "Auto Scaling", "Serverless",
        "Containers", "Docker", "Kubernetes", "CI/CD", "Monitoring",
        "Mini Projects", "Advanced Projects",
    ],
}

TARGET_ROLES = [
    "Software Developer", "Frontend Developer", "Backend Developer",
    "Full Stack Developer", "Data Analyst", "Data Scientist",
    "Machine Learning Engineer", "AI Engineer", "DevOps Engineer",
    "Cloud Engineer", "Cyber Security Analyst", "Mobile App Developer",
]
